version: '3.8'

services:
    notes:
        build:
            context: .
        ports:
            - 3000:3000
            - 9229:9229
        environment:
            - SERVER_PORT=3000
            - CONNECTIONSTRING=mongodb://mongo:27017/notes
            - LOG_NAME=ADDED_VOLUME_TEST
        volumes:
            - ./:/app
            - /etc/todos:/etc/todos
        command: npm run debug
